I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script
    show  max with zoom(0.8)
  File "game/script.rpy", line 77, in <module>
    show  max with zoom(0.8)
NameError: name 'zoom' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script
    show  max with zoom(0.8)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 77, in <module>
    show  max with zoom(0.8)
NameError: name 'zoom' is not defined

macOS-13.4-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
The Killer Date 1.0
Fri Nov 15 13:21:48 2024
